model_params:
  vocab_size: 32000

training_params:
  train_f: 'corpora/livedoor/train.tsv'
  valid_f: 'corpora/livedoor/valid.tsv'
  model_prefix: 'corpora/jawiki/spm'
  batch_size: 8
  n_workers: 0
  max_epochs: 10
  log_every_n_steps: 2

